### ISSUE TITLE
History tab do not track Bonus Lists

### ISSUE THREAD

**Issue by Meltinnglava** [jrob8577/Auctionator#54]
Bug part:
I am trying to sell my Grips of Vicious Mauling. There are one on the auction house that is normal, thow i want to sell my mythic one. Since there are no mythic in the auction house, it wants to make the price of the mythic gloves, the same as the normal ones. 

Enhancement part: 
When auctionator does not find any matching items, it will show you the items that nearly match in the auction house

**Comment by jrob8577** [comment]
@Meltinnglava We're currently testing a fix to this; I've changed the ID we use to internally track items to add the tier as part of the uniqueness of an item.  Send me your email and I can send you a copy to test.

**Comment by Meltinnglava** [comment]
meltinglavaoutland@gmail.com

**Comment by Meltinnglava** [comment]
Ok. so after a few days of not playing, i downloaded the new fix.
This time i was not the only one that had the mythic item out on AH. It shows in current (as espected), thow it is warforged. So the tracer is probably not tracking more than one Bonus List. History tab looks good, as it does not show the normal versions that is on the AH.

For enhance/fix. Make a new collom in the History tab next to date https://gyazo.com/89f62cd3081ab065b02787926c8e2696 , that says note to be like (wf, socet, leech, wf +socet). That would also be nice in Current tab, and Buy tab (between current Auctions and Stack price)

Hope i made myself understandable
Meltinglava

**Comment by jrob8577** [comment]
Given all of the changes for Legion readiness, closing older tickets.  Please re-open if it happens again, with BugGrabber/BugSack details!  We've added some updates around upgraded items, as well, which may have addressed this issue.
