### ISSUE TITLE
Log out delays

### ISSUE THREAD

**Issue by Luthias08** [jrob8577/Auctionator#55]
Recently with Auctionator I have been getting log out delays, could there be something I am missing or not doing that has caused this to start happening? I have gone through the process of elimination with my addons and it only occurs once I select the auctionator addon.

**Comment by jrob8577** [comment]
Thanks for the report, not sure how I missed it... must have notifications set incorrectly.  :frowning: 

If you got to the settings for Auctionator:
Interface > Addons > Auctionatory > Basic Options

And select the "Enable debug mode" option, you'll at least see what the activity is that Auctionator is doing at logout.  I suspect you have a ton of data that is getting saved, but it's hard to say without being able to reproduce your logout environment.  Be warned that debug mode is super spammy in your chat box (it basically logs every time Auctionator does anything interesting)... I'll have to think about how to make it so we can store the output after the game exits, but maybe you can try to screen cap as you log so I can see what is happening?

**Comment by jrob8577** [comment]
Closing, no response
