### ISSUE TITLE
Issues with opening bag

### ISSUE THREAD

**Issue by Zwixx** [jrob8577/Auctionator#56]
If I open the auction window my arkinventory opens the bags too. If I now go to the sell window, auctionator closes my bags and I have to reopen it. A check that's the bags are already open, would be good.

**Comment by jrob8577** [comment]
This came up again in a recent issue. Unfortunately, the blizzard API does not expose behavior that allows me to check for open bags.  I did change the behavior so that opening bags could be enabled or disabled for all characters at once, instead of per toon.
