### ISSUE TITLE
Sell tab error 1300

### ISSUE THREAD

**Issue by zOrgpbp** [jrob8577/Auctionator#57]
Interface\AddOns\Auctionator\Auctionator.lua:1300: attempt to index global 'AtrScanningTooltip' (a nil value)
------------
VERS:3.2.6   MEM:  1502 KB   DB:733   SE:0  SL:2  FSCHUNK:<nil>  DBVERS:4
------------
REALMS: , Kazzak_Neutral (0), Outland_Alliance (3), Kazzak_Horde (733), Sylvanas_Alliance (0), Ravencrest_Alliance (0)
------------
STACK: Atr_GetSellItemInfo > Atr_OnNewAuctionUpdate > Atr_EventHandler > ClickAuctionSellItemButton > Atr_ClickAuctionSellItemButton
------------
ADDONS: , _NPCScan, AngryAssignments, AtlasLoot, Auctionator, AutoLog, CrossRealmAssist, ExRT, Forte_Core, Forte_Casting, Forte_Class, Forte_Cooldown, Forte_Timer, Forte_Talent, Peace, Grid, HandyNotes, IskarAssist, MacroToolkit, MapCoords, MasterPlanA, MikScrollingBattleText, OmniCC, Postal, Prat-3.0, Prospect, Quartz, SellOMatic2, SexyMap, Skada, TidyPlates, TitanBag, TitanClock, TitanGold, TitanLocation, TitanLootType, TitanPerformance, TitanRepair, TitanVolume, TitanXP, Titan, TomTom, ZPerl, DBM

**Comment by jrob8577** [comment]
Unable to reproduce.  With all of the changes for Legion, this bug report can't be traced back to source of origin anymore either.  Will close, re-open if encountered again in Legion.
