### ISSUE TITLE
WoW Crashed mid LFR fight, bug details available

### ISSUE THREAD

**Issue by saudf** [jrob8577/Auctionator#61]
Interface\AddOns\Auctionator\AuctionatorScan.lua:1481: script ran too long
------------
VERS:3.2.6   MEM: 16656 KB   DB:37862   SE:0  SL:2  FSCHUNK:<nil>  DBVERS:4
------------
REALMS: , Stormrage_Alliance (37862)
------------
STACK: pairs > Atr_PruneScanDB > Atr_InitScanDB > Atr_OnLoad > Atr_EventHandler
------------
ADDONS: , _NPCScan, AchievementsReminder, AckisRecipeList, Altoholic, Archy, AshranBuddy, AskMrRobot, Auctionator, DataStore, Factionizer, GTFO, HandyNotes, LFRAdvanced, MasterPlanA, MikScrollingBattleText, Overachiever, PetTracker, RaidAchievement, Rarity, SavedInstances, Skada, TomTom, WeakAuras, +Wowhead_Looter, ElvUI, DBM

**Comment by jrob8577** [comment]
Given all of the changes for Legion readiness, closing older tickets.  Please re-open if it happens again, with BugGrabber/BugSack details!
