### ISSUE TITLE
 Interface\AddOns\Auctionator\Auctionator.lua:416: script ran too long

### ISSUE THREAD

**Issue by saudf** [jrob8577/Auctionator#62]
Interface\AddOns\Auctionator\Auctionator.lua:416: script ran too long
------------
VERS:3.2.6   MEM: 16065 KB   DB:46750   SE:0  SL:2  FSCHUNK:<nil>  DBVERS:4
------------
REALMS: , Stormrage_Alliance (46750)
------------
STACK: collectgarbage > Atr_GetAuctionatorMemString > atr_onShow > Show > InterfaceOptionsList_DisplayPanel > InterfaceOptionsListButton_OnClick
------------
ADDONS: , _NPCScan, AchievementsReminder, AckisRecipeList, Altoholic, Archy, AshranBuddy, AskMrRobot, Auctionator, DataStore, Factionizer, GTFO, HandyNotes, LFRAdvanced, MasterPlanA, MikScrollingBattleText, Overachiever, PetTracker, RaidAchievement, Rarity, SavedInstances, Skada, TomTom, WeakAuras, +Wowhead_Looter, ElvUI, DBM

**Comment by jrob8577** [comment]
Given all of the changes for Legion readiness, closing older tickets.  Please re-open if it happens again, with BugGrabber/BugSack details!
