### ISSUE TITLE
Index field '?'

### ISSUE THREAD

**Issue by Mythotical** [jrob8577/Auctionator#63]
Interface\AddOns\Auctionator\AuctionatorConfig.lua:1107: attempt to index field '?' (a nil value)
------------
VERS:3.2.6   MEM:  1044 KB   DB:24   SE:1  SL:1  FSCHUNK:<nil>  DBVERS:4
------------
REALMS: , Korialstrasz_Horde (0), Malorne_Alliance (3), Eldre'Thalas_Horde (24)
------------
STACK: OnShow > StaticPopup_OnShow > Show > StaticPopup_Show
------------
ADDONS: , _NPCScan, ACP, Altoholic, AskMrRobot, Auctionator, BagBrother, Bagnon, BattlePetCount, BittensSpellFlash_KeyBindings, BittensSpellFlashLibrary, bosseskilled, CollectMe, DataStore, Decursive, DailyGlobalCheck, DraenorTreasures, Factionizer, FloAspectBar, FloTotemBar, fuba_TanaanObjectives, Gatherer, GuildCheck, HandyNotes, Leatrix_Plus, MapNotes, MinimapButtonFrame, MoveAnything, MozzFullWorldMap, MyRareFinder, PallyPower, PetBattleTeams, PetTracker, PokemonTrainer, Postal, RareSpawnOverlay, Rarity, ServerHop, Skada, SpellFlashCore, StatBlock_Memory, TheUndermineJournal, TitanCurrTrack, TitanReputation, TitanAlchemy, TitanArchaeologyFragments, TitanArchaeology, TitanBlacksmithing, TitanCooking, TitanEngineering, TitanFirstAid, TitanFishing, TitanGuild, TitanHerbalism, TitanLeatherworking, TitanMining, TitanSkinning, TitanTailoring, TitanWarforgedSeals, TitanMail, TitanSpec, TitanBag, TitanClock, TitanCurrency, TitanGold, TitanLocation, TitanLootType, TitanPerformance, TitanPoints, TitanRecZone, TitanRepair, TitanVolume, TitanWorkOrders, TitanXP, Titan, TomTom, tradeskillmaster_tdautovendoring, VuhDo, WoWDBProfiler, TradeSkillMaster, Zotwee, SpellFlash, DBM, SuperGuildInvite

**Comment by jrob8577** [comment]
Thanks for the bug report, hoping a bunch of these pop up as I dig in to Legion testing!

**Comment by jrob8577** [comment]
Given all of the changes for Legion readiness, closing older tickets.  Please re-open if it happens again, with BugGrabber/BugSack details!
