### ISSUE TITLE
Request: sold statistic data

### ISSUE THREAD

**Issue by alishahb** [jrob8577/Auctionator#65]
Love this addon! Will be so great if you can add module to collect & show auctions sold / expire statistic of your auctions per server.

**Comment by jrob8577** [comment]
Once I get through Legion testing, I can look into new features like this, thanks for the request!!

**Comment by jrob8577** [comment]
@alishahb Can you be more specific about what you mean by collecting and showing sold / expire statistics?  
* What numbers do you think should be collected? 
* What statistics should be collected, calculated, aggregated?
* Where in the UI should they be shown?

Closing, but please re-open with more detail!
