### ISSUE TITLE
Legion eror opening tradeskill window

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#69]
Didn't even think of this until I opened my trade skill window in beta. Looks like that frame is renamed but I haven't searched what if any replace to fix it will be.

Auctionator\Auctionator-4.0.0.lua:717: Auctionator_Search:SetPoint(): Couldn't find region named 'TradeSkillDetailScrollChildFrame'
[C]: in function `SetPoint'
Auctionator\Auctionator-4.0.0.lua:717: in function <Auctionator\Auctionator.lua:705>
Auctionator\Auctionator-4.0.0.lua:965: in function `Atr_OnAddonLoaded'
Auctionator\Auctionator-4.0.0.lua:184: in function `Atr_EventHandler'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:450: in function `TradeSkillFrame_LoadUI'
FrameXML\UIParent.lua:1453: in function <FrameXML\UIParent.lua:891>

Locals:
(*temporary) = Auctionator_Search {
 0 = <userdata>
 Right = <unnamed> {
 }
 Left = <unnamed> {
 }
 Middle = <unnamed> {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = "TradeSkillDetailScrollChildFrame"
(*temporary) = "TOPRIGHT"
(*temporary) = -1
(*temporary) = -24

**Comment by ceylina** [comment]
Ok so if you change line 725 and 726 to this

    local button = CreateFrame("BUTTON", "Auctionator_Search", TradeSkillFrameScrollChild, "UIPanelButtonTemplate");
    button:SetPoint("TOPRIGHT", "TradeSkillFrameScrollChild", "TOPRIGHT", -3, -12);


it works but... they changes all the tradeskill functions so looks like more work :(

**Comment by ceylina** [comment]
so here is what I have found about hte tradeskill functions:
This pertains to auctionator.lua
Starting at line 671

local index = GetTradeSkillSelectionIndex()
This is the big issue. I guess if you could match a list name to the recipeid and somehow match that to the selected recipe name you could use n array to find the match ot the selected. I can't find anything that replaces this directly.

local link = GetTradeSkillItemLink(index)

this becomes (direct replacement)

local link = C_TradeSkillUI.GetRecipeItemLink(index)


local numReagents = GetTradeSkillNumReagents (index)

direct replacement:

local numReagents = C_TradeSkillUI.GetRecipeNumReagents(index)


  local shoppingListName = GetItemInfo (link)
  if (shoppingListName == nil) then
    shoppingListName = GetTradeSkillInfo (index)
  end

GetTradeSkillInfo  has no direct replacement so it would be a bit of work to get it in legion. Perhaps it is safe to just remove the check and put in

local shoppingListName = GetItemInfo (link)

local reagentName = GetTradeSkillReagentInfo(index, reagentId)

direct replacement

local reagentName = C_TradeSkillUI.GetRecipeReagentInfo(index, reagentId)


So the only issue is making some sort of loop to check against the list of recipe ids for the tradeskill then somehow match up against he selected tradeskill and output the correct id

Either of these two will create a table of IDs

C_TradeSkillUI.GetAllRecipeIDs() or C_TradeSkillUI.GetFilteredRecipeIDs

**Comment by jrob8577** [comment]
I think we fixed this, closing.
