### ISSUE TITLE
AuctionatorHints.lua mailbox hook changes

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#72]
The error was reported as

Auctionator\AuctionatorHints.lua:1177: Usage: GetInboxItem(messageIndex, attachIndex)
[C]: in function `GetInboxItem'
Auctionator\AuctionatorHints.lua:1177: in function <Auctionator\AuctionatorHints.lua:1176>
[C]: in function `SetInboxItem'
FrameXML\MailFrame.lua:300: in function `InboxFrameItem_OnEnter'
Postal\Modules\Express.lua:42: in function <Postal\Modules\Express.lua:41>
(tail call): ?
[string "​*:OnEnter"]:1: in function <[string "*​:OnEnter"]:1>

Locals:
(*temporary) = 6
(*temporary) = nil

There may be more but for now these are the changes needed to update to legion

In AuctionatorHints.lua

**Line 1177**

Change

`local _, _, num = GetInboxItem(index, attachIndex);`

to

`local _, _, _, num = GetInboxItem(index, attachIndex);`

**Line 1184**

Change

`local name, _, num = GetSendMailItem(id)`

to

`local name, _, _, num = GetSendMailItem(id)`

**Comment by jrob8577** [comment]
Fixed in release F
