### ISSUE TITLE
DE tootlip info not showing for armor types

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#77]
DE info for pricing and what DEing an item breaks down into shows fine if the item is weapon but armor is not showing at all.

It will still show unknown on the beta if there are no DE mats for sale on the AH but the break down information will show.

**Comment by ceylina** [comment]
One more thing to add.. It seems it is pulling up the disenchant tooltip entry for armor but is not showing pricing information which then does not show what the items breaks down into.

**Comment by ceylina** [comment]
So it seems auctionator.lua and auctionatorhints.lua had some local variables defines as WEAPON and ARMOR. They had values assigned as 1 and 2 respectively.

Changing them to 

local WEAPON = LE_ITEM_CLASS_WEAPON;
local ARMOR  = LE_ITEM_CLASS_ARMOR;

which means weapon=2 and armor=4 (the classID of these top level auction classes) fixed the issue.

**Comment by jrob8577** [comment]
Should be updated in most recent version with disenchanting refactoring (note that ilevels still not accurate, but that's captured in another ticket)
