### ISSUE TITLE
AuctionatorHints.lua needs hardcoded enchanting mats information for legion

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#78]
After line 301 (local DRAENIC_DUST      = 109693) add

local ARKHANA    = 124440;
local LEYLIGHT_SHARD  = 124441;
local CHAOS_CRYSTAL   = 124442;

After line 381 (engDEnames[DRAENIC_DUST]    = 'Draenic Dust') add

engDEnames[ARKHANA]  = 'Arkhana';
engDEnames[LEYLIGHT_SHARD]  = 'Leylight Shard';
engDEnames[CHAOS_CRYSTAL]   = 'Chaos Crystal';

After line 453 (tinsert (dustsAndEssences, DRAENIC_DUST) add

tinsert (dustsAndEssences, ARKHANA)
tinsert (dustsAndEssences, LEYLIGHT_SHARD)
tinsert (dustsAndEssences, CHAOS_CRYSTAL)

There is also this section:

function Atr_InitDETable()

This needs also the updated table info for legion but I do not know the structure (no comment on how it is laid out)

For example:

DEtableInsert (t, {484,700    , 100, 2.5, DRAENIC_DUST})

This needs to be done for legion mats as well and I pretty much assume that the first and second number there are ilevel ranges, the third is most likely percent chance of it being broken down into the item of items but not sure the last number.

So it would be something like this?

DEtableInsert (t, {701,875    , 100, 2.5, ARKHANA}) - actually I have no idea what the max ilevel of items that can be DE'd is it 905?

**Comment by ceylina** [comment]
After finding a fix for #77 I noticed there is something not capping items level or player level items at draenor crystals and as such anything level 101 up still shows WoD crystals as de items. Will have to look into this one.

**Comment by ceylina** [comment]
found possible fix for item level issue with disenchanting. Will post new ticket

**Comment by jrob8577** [comment]
Added in the new `Auctionator.Constants.Disenchanting`* files - see Source/Constants
