### ISSUE TITLE
Format issue in auctionatorlocalize.lua line 279

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#79]
local _, _, _, _, _, _, _, _, _, _, _ itemClassID, itemSubClassID = GetItemInfo( itemLink )

Should it not be 

local _, _, _, _, _, _, _, _, _, _, _, itemClassID, itemSubClassID = GetItemInfo( itemLink )

a comma after that last underscore

**Comment by jrob8577** [comment]
Fixed.
