### ISSUE TITLE
Item Level scaling innacurate with WOD & legion gear - possible fix for DE info

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#80]
With the introduction of item upgrades late in MoP carrying through Wod and into Legion and beyond, getItemInfo(0 no longer offers accurate item level scaling information. This means that the disenchant information, which relies on item level or armor and weapons to calculate what mats are DE'd, will no be accurate from MoP gear onward.

A library has been created to handle the complexities of item level scaling.

http://www.wowace.com/addons/libitemupgradeinfo-1-0/

This has been talk around different forums for a while and the consensus seems to be to use this library. It does not rely on ace libraries outside of libstub.

To accomplish accurate scanning of gear and displaying proper disenchanting information, here is what I am testing:

Download libitemupgradeinfo

Make a folder in the root of Auctionator called Libs

Put the extracted folder LibItemUpgradeInfo-1.0 into it (containing the folder and files for LibStub and the library files)

In Auctionator.toc, add the following before Locales

Libs\LibItemUpgradeInfo-1.0\LibItemUpgradeInfo-1.0.xml

In AuctionatorHints.lua after line 6 add

local ItemUpgradeInfo = LibStub("LibItemUpgradeInfo-1.0")

after line 1007 )1008 after you add the library link)
(after this local itemName, itemLink, itemRarity, itemLevel, itemMinLevel, itemType, _, _, _, _, itemVendorPrice, classID = GetItemInfo (link);)

add

itemLevel = ItemUpgradeInfo:GetUpgradedItemLevel(itemLink)

Why do this? Because in AuctionatorHinst.lua there is a database table created using item levels of gear to calculate what mats they DE into. After somewhere above item level 500ish (around SOO), these start to become wildly inaccurate and can report he level wrong if near the cusp of an item level range for an expansion. Meaning item level 750 gear can report as say 715 thus being under the range for WoD gear and reporting the wrong mats.

Using this library means you get a better estimate of items and thus more accurate disenchanting information.

Some reference posts:
http://www.wowinterface.com/forums/showthread.php?t=52889
http://www.wowinterface.com/forums/showthread.php?t=46543
http://www.wowinterface.com/forums/showthread.php?t=45388
http://us.battle.net/wow/en/forum/topic/7199032730#9

**Comment by jrob8577** [comment]
Thanks for all the great research and work on this issue!  Most recent build has this included, and appears to be working for me.  😄
