### ISSUE TITLE
Full scan not scanning past first page

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#82]
Full scan (not slow scanning) is only returning 50 auctions scanned. Meaning it is only scanning the first page and not the entire AH.

**Comment by ceylina** [comment]
minor change was done to QueryAuctionItems

in AuctionatorScanFull.lua

Line 93

change 

QueryAuctionItems ("", nil, nil, 0, nil, nil, false, false, nil);

to 

QueryAuctionItems ("", nil, nil, 0, 0, 0, 0, 0, 0);

and change line 143

QueryAuctionItems ("", nil, nil, gSlowScanPage, nil, nil, false, false, nil)

to 

QueryAuctionItems ("", nil, nil, gSlowScanPage, 0, 0, 0, 0, 0)

**Comment by jrob8577** [comment]
This has been updated in the most recent build, closing.
