### ISSUE TITLE
Show how many pages have refresh not only actual page

### ISSUE THREAD

**Issue by esvarc** [jrob8577/Auctionator#84]
On "buy" and "sell" page I would like to have information about how many pages would be fetched from server. I did modded original addon with change listed bellow and I would like to have implemented in main branch and won't need patch your source when you release new version.

in AuctionatorScan.lua at line 422
`    msg = string.format (ZT("Scanning auctions: page %d of %d"), self.current_page, math.floor (q.totalAuctions/ 50) + 1); 
`

**Comment by ceylina** [comment]
I will test this on the legion beta and make sure it doesn't cause over head. Please note that with the legion pre patch coming very soon, development on the current live version has migrated to legion compatibility (due mostly to the large number of changes in legion).

**Comment by ceylina** [comment]
Fixed and updated into legion update.
