### ISSUE TITLE
Better placing elements at sell page

### ISSUE THREAD

**Issue by esvarc** [jrob8577/Auctionator#85]
I did moded Auctionator.xml to better suit "Per Item" input boxes and "Create %d Auctions" button, actually these overlap and or not suit frame.

Line 600, 604 and 739 to 740 in Auctionator.xml

AbsDimension x="10" y="-70" original x="10" y="-82"
AbsDimension x="10" y="-110" original x="10" y="-128"
AbsDimension x="180" y="30" original x="185" y="30"
AbsDimension x="7" y="-150" original x="3" y="-170"

Sorry I did must remove all XML tags, because then wasn't properly formated here even I did use CODE tag.

I'm not sure if this is not scaling problem so I put here my UIScale and screen dimension, 0.64 and 1920 by 1200 so ratio is 16:10.

**Comment by ceylina** [comment]
The xml layout for Auctionator has been revamped and may no longer overlap come Legion. If the version that will be compatible after the pre patch still does this, please raise a new issue.
