### ISSUE TITLE
Rise limit for auctions in scan

### ISSUE THREAD

**Issue by esvarc** [jrob8577/Auctionator#86]
Actually is really common that AH on my server for certain item having hundreds of items for sale with stack size 1. So it leads in huge amount actions even for narrow search of single item. To make Auctionator working I must mod limit in code in file AuctionatorScan.lua at line 402

` if (self.current_page == 1 and q.totalAuctions > 10000) then`

Instead setting value inside code it would be nice have it configurable, because 5000 limit in your code is really too low especially for bussy realm.

**Comment by ceylina** [comment]
Reviewing upping this to 10000 as a limit. That will allow 200 page searches (up from 100).

We still want to throttle excessive searches to prevent placing too much load on the servers. If you are encountering a search of more than the set page limit, please use the advanced filter options and more specific search criteria. For example searching "ore" may not be as specific as "blackrock ore".

**Comment by ceylina** [comment]
Raised to 10000. This allows 200 page searches which should be more than enough for scanning.
