### ISSUE TITLE
Reminder LibItemUpgradeInfo-1.0

### ISSUE THREAD

**Issue by ceylina** [jrob8577/Auctionator#95]
Just a reminder that LibItemUpgradeInfo-1.0 has been patched with our suggested fix. No need to patch it as it is the exact fix we are using but just a heads up to keep tabs while Legion rolls out

http://www.wowace.com/addons/libitemupgradeinfo-1-0/files/

**Comment by jrob8577** [comment]
This should be in the current build. (I did it this morning)
